### ISSUE TITLE
NestedEntityListAttribute should not extend NestedEntityAttribute

### ISSUE THREAD

**Issue by graste** [daikon-cqrs/entity#1]
* introduce interface like `TraversableValueObject`
* `NestedEntityListAttribute` should not extend `NestedEntityAttribute` anymore
* add traits to implement behavior and use that for the `NestedEntityListAttribute` and `NestedEntityAttribute`
* make our default impls `final`

This allows for own implementations in projects like: `get('content_objects')` returning `ContentObjectList` having a similar implementation as `NestedEntityListAttribute` code.

**Comment by shrink0r** [comment]
Fixed in #ed53b1b
